# Generated by Django 4.2.7 on 2026-01-02 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_question_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Document Title')),
                ('file', models.FileField(upload_to='user_documents/', verbose_name='Document File')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('file_size', models.IntegerField(default=0, verbose_name='File Size (bytes)')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='questionnaire.answer', verbose_name='Answer')),
            ],
            options={
                'verbose_name': 'User Document',
                'verbose_name_plural': 'User Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
