# Generated by Django 5.2.8 on 2026-01-20 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_category_environmental_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='choices',
            field=models.ManyToManyField(blank=True, related_name='answers_multiple', to='questionnaire.choice', verbose_name='Selected Choices (Multiple)'),
        ),
        migrations.AddField(
            model_name='question',
            name='allow_multiple',
            field=models.BooleanField(default=False, help_text='Allow users to select multiple answers', verbose_name='Allow Multiple Choices'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaire.choice', verbose_name='Selected Choice (Single)'),
        ),
    ]
