# Generated by Django 5.2.5 on 2026-02-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0009_rename_esg_grade_to_overall_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes or comments for this answer', null=True, verbose_name='Notes/Comments'),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
