# Generated by Django 4.2.7 on 2026-01-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_alter_answer_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='attachment',
            field=models.FileField(blank=True, upload_to='question_attachments/', verbose_name='Question Attachment'),
        ),
    ]
