# Generated by Django 4.2.7 on 2026-01-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_userdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='environmental_weight',
            field=models.FloatField(default=0.0, verbose_name='Environmental Weight'),
        ),
        migrations.AddField(
            model_name='category',
            name='governance_weight',
            field=models.FloatField(default=0.0, verbose_name='Governance Weight'),
        ),
        migrations.AddField(
            model_name='category',
            name='max_score',
            field=models.IntegerField(default=100, verbose_name='Maximum Score'),
        ),
        migrations.AddField(
            model_name='category',
            name='social_weight',
            field=models.FloatField(default=0.0, verbose_name='Social Weight'),
        ),
        migrations.AddField(
            model_name='questionnaireattempt',
            name='environmental_score',
            field=models.FloatField(default=0.0, verbose_name='Environmental Score'),
        ),
        migrations.AddField(
            model_name='questionnaireattempt',
            name='esg_grade',
            field=models.CharField(blank=True, max_length=2, verbose_name='ESG Grade'),
        ),
        migrations.AddField(
            model_name='questionnaireattempt',
            name='governance_score',
            field=models.FloatField(default=0.0, verbose_name='Governance Score'),
        ),
        migrations.AddField(
            model_name='questionnaireattempt',
            name='social_score',
            field=models.FloatField(default=0.0, verbose_name='Social Score'),
        ),
    ]
