# Generated by Django 5.2.8 on 2026-01-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0008_survey_alter_question_options_question_survey_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaireattempt',
            name='esg_grade',
        ),
        migrations.AddField(
            model_name='questionnaireattempt',
            name='overall_grade',
            field=models.CharField(blank=True, max_length=2, verbose_name='Overall Grade'),
        ),
    ]
