# Generated by Django 4.2.7 on 2025-11-19 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyprofile',
            options={'verbose_name': 'Company Profile', 'verbose_name_plural': 'Company Profiles'},
        ),
        migrations.AlterModelOptions(
            name='membershiphistory',
            options={'ordering': ['-start_date'], 'verbose_name': 'Membership History', 'verbose_name_plural': 'Membership Histories'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='additional_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Additional Data'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='address',
            field=models.TextField(blank=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_name',
            field=models.CharField(max_length=200, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='employee_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Employee Count'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='industry',
            field=models.CharField(blank=True, max_length=100, verbose_name='Industry'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='logo',
            field=models.ImageField(blank=True, upload_to='company_logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Registration Number'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='website',
            field=models.URLField(blank=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='membershiphistory',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='membershiphistory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='membershiphistory',
            name='membership_type',
            field=models.CharField(max_length=10, verbose_name='Membership Type'),
        ),
        migrations.AlterField(
            model_name='membershiphistory',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='membershiphistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_history', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Registration Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='membership_type',
            field=models.CharField(choices=[('free', 'Free'), ('silver', 'Silver'), ('gold', 'Gold')], default='free', max_length=10, verbose_name='Membership Type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone'),
        ),
    ]
