# Generated by Django 4.2.7 on 2025-11-19 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تولید')),
                ('pdf_file', models.FileField(blank=True, upload_to='reports/', verbose_name='فایل PDF')),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='questionnaire.questionnaireattempt', verbose_name='تلاش')),
            ],
            options={
                'verbose_name': 'گزارش',
                'verbose_name_plural': 'گزارش\u200cها',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان بخش')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='reports.report', verbose_name='گزارش')),
            ],
            options={
                'verbose_name': 'بخش گزارش',
                'verbose_name_plural': 'بخش\u200cهای گزارش',
                'ordering': ['order'],
            },
        ),
    ]
