# Generated by Django 4.2.7 on 2025-11-19 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_alter_answer_options_alter_category_options_and_more'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-generated_at'], 'verbose_name': 'Report', 'verbose_name_plural': 'Reports'},
        ),
        migrations.AlterModelOptions(
            name='reportsection',
            options={'ordering': ['order'], 'verbose_name': 'Report Section', 'verbose_name_plural': 'Report Sections'},
        ),
        migrations.AlterField(
            model_name='report',
            name='attempt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='questionnaire.questionnaireattempt', verbose_name='Attempt'),
        ),
        migrations.AlterField(
            model_name='report',
            name='generated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Generated At'),
        ),
        migrations.AlterField(
            model_name='report',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to='reports/', verbose_name='PDF File'),
        ),
        migrations.AlterField(
            model_name='reportsection',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='reportsection',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='reportsection',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='reports.report', verbose_name='Report'),
        ),
        migrations.AlterField(
            model_name='reportsection',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Section Title'),
        ),
    ]
